

persistence true # 지속성 활성화
persistence_location /mosquitto/data/ # 지속성 데이터 저장 경로
log_dest file /mosquitto/log/mosquitto.log # 로그 파일 저장 경로
log_dest stdout # 로그 출력
log_type all # 로그 타입 전체


# 외부 연결은 서버가 브로커 역할수행 -> 설정필요x

# 1. Internal Listener (로컬 통신용)
listener 1883 # 로컬 통신용
allow_anonymous false  # id/pw 비밀번호 인증 적용 
password_file /mosquitto/config/passwd





